### ISSUE TITLE
Support shorter syntax

### ISSUE THREAD

**Issue by fakenickels** [Astrocoders/bs-epitath#1]
```
let%Epitath form = <Form />
```

**Comment by medson10** [comment]
Hmmm did you mean this be the new usage? Because look like it will limit the usage in some cases

**Comment by boyswan** [comment]
Had a play around with this too but can't quite figure it out. Any progress?

**Comment by fakenickels** [comment]
Nice @boyswan , I didn't started trying out how to yet. 
Would you mind pasting here your try outs on this? 🤔
